//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiqPayServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rl_liqpay_donate_info
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Order_id { get; set; }
        public string Action { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency { get; set; }
        public Nullable<decimal> Subscribe_amount { get; set; }
        public string Subscribe_date_start { get; set; }
        public string Subscribe_periodicity { get; set; }
        public string Signature { get; set; }
        public string Status { get; set; }
        public string JsonData { get; set; }
        public Nullable<decimal> Sender_commission { get; set; }
        public Nullable<decimal> Receiver_commission { get; set; }
        public Nullable<decimal> Agent_commission { get; set; }
        public string Sender_card_country { get; set; }
        public string Ip { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> PaimentDate { get; set; }
        public string TypeOfPayer { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
    }
}
